system:
  env: debug
  addr: 8081
mysql:
  dns: root:@(127.0.0.1:3306)/lebron?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleConns: 30
  maxOpenConns: 100
  connMaxIdleTime: 3600
  connMaxLifetime: 0
redis:
  host: 127.0.0.1
  pass:
  port: 6379
  db: 1
  idleTimeout: 10
jwt:
  issuer: gapi
  ttl: 604800
  secret: g0EiVz@TJvAX2MKq1LRhB6bFw3u8Zs5#H%e!pj
logger:
  path: ./logs/app.log
  level: 1
  maxSize: 5
  maxBackups: 10
  maxAge: 14
  compress: true
